---
title: "Text Analysis Visualization Essay"
author: "Justin Broubalow"
date: "April 24, 2017"
output: html_document
---

```{r, message=FALSE, echo=FALSE}
library(quanteda)
library(tidytext)
library(tidyverse)
library(scales)
library(stringr)
library(wordcloud)
library(viridis)
library(grid)
library(testthat)
library(magrittr)
library(methods)
```


```{r, warning=FALSE, echo=FALSE}
trump <- paste(readLines("D:/clio-II/text-analysis-viz-essay/trump-inaug.txt"),
               collapse = " ")
trump_df <- data_frame(fulltext = trump,
                       inauguration = "2017-Trump")

inaugurals <- data_frame(fulltext = inaugTexts,
			inauguration = names(inaugTexts)) %>%
  rbind(trump_df) %>% 
   mutate(year = as.numeric(str_sub(inauguration, 1, 4)),
          president = str_sub(inauguration, start = 6)) %>%
   unnest_tokens(word, fulltext, token = "words") %>%
   group_by(inauguration) %>%
   mutate(sequence = 1:n()) 

```

```{r, echo=FALSE}
word_count <- inaugurals %>%
   group_by(inauguration, word, year, president) %>%
   summarize(count = n()) %>%
   bind_tf_idf(word, inauguration, count) %>%
   ungroup()


expect_equal(nrow(inaugurals), sum(word_count$count))

all_counts <- word_count %>%
   group_by(word) %>%
   summarize(total_count = sum(count)) %>%
   arrange(desc(total_count))

expect_equal(sum(all_counts$total_count), sum(word_count$count))

word_count <- word_count %>%
   left_join(all_counts, by = "word")

inaugs <- unique(inaugurals$inauguration)
   
```

```{r, echo=FALSE, message=FALSE}
presidents <- read.csv("D:/clio-II/text-analysis-viz-essay/presidents.csv",
                       skip = 3, stringsAsFactors = FALSE) %>%

   select(inauguration)


word_count %>%
   mutate(word = ifelse(grepl("americ", word), "america", word),
          word = ifelse(grepl("democra", word), "democracy", word),
          word = ifelse(grepl("protect", word), "protect", word),
          word = ifelse(grepl("free", word), "free", word)) %>%
   group_by(inauguration, president, year, word) %>%
   summarize(count = sum(count)) %>% 
   group_by(inauguration, president, year) %>%
   mutate(relative_count = count / sum(count)) %>%
   filter(word %in% c("america", "free", "democracy", "protect")) %>%
   left_join(presidents, by = "inauguration") %>% 
   ggplot(aes(x = year, y = relative_count)) +
   geom_line() +
  geom_point() +
   facet_wrap(~word, scales = "free_y") +
   ggtitle("Changing use of selected words in inaugural addresses",
           "Presidents labeled if they used the word or a variant.") +
   labs(x = "", y = "Number of times used as a percentage of all words") +
   scale_y_continuous(label = percent)
  
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
set.seed(123)
par(family = "", bg = "black", mfrow = c(2, 2))
recent_inaugs <- c("1993-Clinton", "2001-Bush", "2009-Obama", "2017-Trump")
cols <- c("steelblue", "darkred", "steelblue", "darkred")
for(i in 1:length(recent_inaugs)){
   new_words <- word_count %>%
      filter(total_count == count) %>%
      filter(inauguration == recent_inaugs[[i]]) %$%
      wordcloud(words = .$word, 
                colors = terrain.colors(15), random.color = TRUE, scale = c(1.1, 0.9))
   title(main = gsub("-", " ", recent_inaugs[[i]]), col.main = cols[i])
}
  
```

